### ISSUE TITLE
Add support for bot API 8.0

### ISSUE THREAD

**Issue by SethuXD** [twa-dev/SDK#36] opened 2024-11-19 03:29 UTC
Telegram just dropped Bot API 8.0
 https://core.telegram.org/bots/api-changelog#november-17-2024.

Can you update the SDK to support the new API version? 

Thanks!

**Comment by jaavid** [comment] 2024-11-21 14:51
@openhands-agent can you fix it ?

**Comment by ennucore** [comment] 2024-11-22 15:06
Is there a workaround until it's updated? There's a [pull request](https://github.com/twa-dev/SDK/pull/34), maybe one can use that version it the meantime, but I haven't been able to make it work

**Comment by ArthurStam** [comment] 2024-11-26 22:37
Duplicate of #32

**Closed** 2024-11-26 22:37 UTC
